baseURL: 'https://winnyace.github.io'
languageCode: en-us
title: winnyace's blog
theme: PaperMod
publishDir: public

params:
  description: winnyace's blog. It's mostly about computers and video games. 
  ShowReadingTime: true
  ShowToc: true
  social: true
  favicon: "favicon.ico"
  homeInfoParams:
    Title: Hi! 👋
    Content: "I'm winnyace. Welcome to my blog! Here, I talk about things that interest me or that I want to share, mainly video games and computers."

  socialIcons:
    - name: "email"
      title: "My email: winnyace@proton.me"
      url: "mailto:winnyace@proton.me"
    - name: "github"
      title: "My GitHub"
      url: "https://github.com/winnyace"
    - name: "codeberg"
      title: "My Codeberg"
      url: "https://codeberg.org/winnyace"


markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: Tags
      name: Tags
      title: tags
      url: /tags/
      weight: 10
