baseURL: 'https://winnyace.github.io'
languageCode: en-us
title: winnyace's blog
theme: PaperMod
publishDir: docs

params:
  description: winnyace's blog. It's mostly about computers and video games. 
  ShowReadingTime: true
  ShowToc: true
  favicon: "favicon.ico"
  homeInfoParams:
    Title: Hi! 👋
    Content: "I'm winnyace, or winny for short. 
    Welcome to my blog!
    Here, I talk about things that interest me or that I want to share, which are mainly video games and computers."

menu:
  main:
    - identifier: contact
      name: Contact
      title: contact
      url: /contact/
      weight: 10
    - identifier: Tags
      name: Tags
      title: tags
      url: /tags/
      weight: 9