baseURL = "https://winnyace.github.io"
languageCode = "en-us"
title = "winnyace's blog"
theme = "etch"
publishDir = "docs"


[menu]
    [[menu.main]]
        identifier = "about"
        name = "about"
        title = "about"
        url = "/about/"
        weight = 10
    [[menu.main]]
        identifier = "contact"
        name = "contact"
        title = "contact"
        url = "/contact/"
        weight = 20
